CREATE DATABASE Project_HomeStay

USE Project_HomeStay

CREATE TABLE Users(
	UserId		INT				PRIMARY KEY IDENTITY(1, 1),
	Username	VARCHAR(100)	NOT NULL UNIQUE,
	Email		VARCHAR(100)	NOT NULL UNIQUE,
	[Role]		VARCHAR(100)	NOT NULL,
	[Password]	VARCHAR(100)	NOT NULL,
	Fullname	NVARCHAR(100)	NOT NULL,
	Gender		BIT,
	[Status]	BIT				NOT NULL
)

CREATE TABLE Homestays(
	HomestayId		INT				PRIMARY KEY IDENTITY(1, 1),
	HomestayName	NVARCHAR(255)	NOT NULL,
	Country			NVARCHAR(255)	NOT NULL,
	City			NVARCHAR(255)	NOT NULL,
	District		NVARCHAR(255)	NOT NULL,
	Commune			NVARCHAR(255)	NOT NULL,
	[Address]		NVARCHAR(255)	NOT NULL,
	[Status]		BIT				NOT NULL,
	[Type]			NVARCHAR(255)	NOT NULL,
	Price			MONEY			NOT NULL,
	[Description]	NVARCHAR(MAX)	NOT NULL
)

CREATE TABLE Discounts(
	DiscountId	INT			PRIMARY KEY IDENTITY(1, 1),
	HomstayId	INT			REFERENCES Homestays(HomestayId) NOT NULL,
	Discount	FLOAT		NOT NULL,
	DateStart	DATETIME	NOT NULL,
	DateEnd		DATETIME	NOT NULL
)

CREATE TABLE Images(
	ImageId		INT				PRIMARY KEY IDENTITY(1, 1),
	HomstayId	INT				REFERENCES Homestays(HomestayId) NOT NULL,
	Link		VARCHAR(MAX)	NOT NULL
)

CREATE TABLE Orders(
	OrderId		INT				PRIMARY KEY IDENTITY(1, 1),
	UserId		INT				REFERENCES Users(UserId) NOT NULL,
	HomestayId	INT				REFERENCES Homestays(HomestayId) NOT NULL,
	OrderDate	DATETIME		NOT NULL,
	[Status]	VARCHAR(100)	NOT NULL
)

CREATE TABLE OrderDetails(
	OrderDetailId	INT			PRIMARY KEY IDENTITY(1, 1),
	OrderId			INT			REFERENCES Orders(OrderId) NOT NULL,
	FromDate		DATETIME	NOT NULL,
	EndDate			DATETIME	NOT NULL,
	PriceWhenSell	MONEY		NOT NULL,
	IsPayment		BIT			NOT NULL
)

CREATE TABLE Services(
	ServiceId		INT				PRIMARY KEY IDENTITY(1, 1),
	ServiceName		NVARCHAR(255)	NOT NULL,
	[Description]	NVARCHAR(MAX)	NOT NULL,
	Price			MONEY			NOT NULL
)

CREATE TABLE OrderServices(
	OrderId		INT			REFERENCES Orders(OrderId) NOT NULL,
	ServiceId	INT			REFERENCES Services(ServiceId) NOT NULL,
	PRIMARY KEY (OrderId, ServiceId)
)